FROM nginx:1.13.6-alpine
LABEL maintainer="EEA: IDM2 A-Team <eea-edw-a-team-alerts@googlegroups.com>"

ARG RIOT_WEB_VERSION="0.13.5"

COPY default.conf /etc/nginx/conf.d/default.conf

RUN set -ex \
    && apk update \
    && apk add --no-cache  \
        curl \
        git \
        libevent \
        libffi \
        libjpeg-turbo \
        libssl1.0 \
        nodejs \
        sqlite-libs \
        ca-certificates \
        openssl \
        bash \
        unzip \
    && npm install -g webpack \
    && curl -L https://github.com/vector-im/riot-web/archive/v${RIOT_WEB_VERSION}.zip -o v.zip \
    && unzip v.zip \
    && rm v.zip \
    && mv riot-web-* /tmp/riot \
    && cd /tmp/riot \
    && npm install \
    && rm -rf /tmp/riot/node_modules/phantomjs-prebuilt/phantomjs
